//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by net_demo.rc
//
#define IDOK2                           3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NET_DEMO_DIALOG             102
#define IDR_HTML_PLAYBACKDIALOG         103
#define IDR_MAINFRAME                   128
#define IDD_PLAYBACK_DIALOG             129
#define IDD_DLG_SET                     130
#define IDD_DLG_OSD                     131
#define IDD_DLG_QUALITY                 132
#define IDD_DLG_ALARM                   133
#define IDD_DLG_MASK_ALARM              134
#define IDD_DLG_WORKSHEET               135
#define IDD_DLG_MOTION                  136
#define IDB_MOTION_MASK                 137
#define IDD_DLG_NET                     138
#define IDD_DLG_SERIAL                  139
#define IDD_DLG_PTZ                     140
#define IDD_DLG_LOG                     141
#define IDD_DLG_REMOTE_DO               142
#define IDD_DLG_SEARCH_DEVICE           143
#define IDD_DLG_CHANNEL_SET             144
#define IDD_DLG_IPC_FEATURE             145
#define IDD_DLG_SUB_QUALITY             146
#define IDD_DLG_VLOST                   147
#define IDB_FOCUS_MASK                  148
#define IDD_DLG_DEVICE_INFO             149
#define IDD_DLG_ALARM_OUT               150
#define IDD_DLG_MASK                    151
#define IDD_DLG_ANALYZE                 152
#define IDD_DLG_CUSTOM_OSD              153
#define IDD_DLG_RECORD_CTRL             154
#define IDD_DLG_KAOQING                 155
#define IDD_RENYUAN_DLG                 156
#define IDD_DLG_RECORD                  157
#define IDD_DLG_VCATCH                  158
#define IDD_IPHOST_DLG                  159
#define IDC_VIDEO                       1000
#define IDC_IPADDRESS1                  1001
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDC_IPADDRESS2                  1003
#define IDC_EDIT3                       1004
#define IDC_BTLOGIN                     1005
#define IDC_EDIT_TIME8                  1005
#define IDC_IPADDRESS3                  1005
#define IDC_EDIT5                       1005
#define IDC_COMBO1                      1006
#define IDC_IPADDRESS4                  1006
#define IDC_EDIT8                       1006
#define IDC_BTCONNECT                   1007
#define IDC_COMBO3                      1007
#define IDC_IPADDRESS5                  1007
#define IDC_EDT_REMOTE_SLOT             1007
#define IDC_COMBO2                      1008
#define IDC_EDIT6                       1008
#define IDC_COMBO4                      1008
#define IDC_IPADDRESS6                  1008
#define IDC_BUTTON1                     1009
#define IDC_BUTTON_SEARCH               1009
#define IDC_BUTTON_PLAYBACK             1009
#define IDC_EDIT4                       1009
#define IDC_COMBO5                      1009
#define IDC_BUTTON2                     1010
#define IDC_BUTTON_START_DOWNLOAD       1010
#define IDC_BUTTON_SET                  1010
#define IDC_EDIT7                       1010
#define IDC_COMBO6                      1010
#define IDC_IP_SNMP                     1010
#define IDC_BUTTON3                     1011
#define IDC_BUTTON_STOP_DWONLOAD        1011
#define IDC_COMBO7                      1011
#define IDC_EDIT_TIME9                  1011
#define IDC_BUTTON_SET2                 1011
#define IDC_EDT_SNMP_INTERVAL           1011
#define IDC_BUTTON4                     1012
#define IDC_BUTTON_PLAY                 1012
#define IDC_COMBO8                      1012
#define IDC_EDIT_TIME4                  1012
#define IDC_BTCONNECT_SUB               1012
#define IDC_BUTTON_PAUSE                1013
#define IDC_EDIT_TIME10                 1013
#define IDC_COMBO11                     1013
#define IDC_BUTTON7                     1013
#define IDC_BTCONNECT2                  1013
#define IDC_EDT_CUSTOM_OSD_DATE_FONT    1013
#define IDC_BUTTON6                     1014
#define IDC_BUTTON_STEP_BACK            1014
#define IDC_EDIT_TIME5                  1014
#define IDC_COMBO12                     1014
#define IDC_BTN_REMOTE_START_REC        1014
#define IDC_BUTTON_STEP_FORWARD         1015
#define IDC_EDIT_TIME11                 1015
#define IDC_COMBO13                     1015
#define IDC_BUTTON8                     1015
#define IDC_BTN_REMOTE_STOP_REC         1015
#define IDC_BUTTON_SPEED                1016
#define IDC_EDIT_TIME6                  1016
#define IDC_BUTTON9                     1016
#define IDC_BTN_REMOTE_ENCODE_ROTATE    1016
#define IDC_BUTTON_SPEED2               1017
#define IDC_BUTTON_SLOW                 1017
#define IDC_EDIT_TIME12                 1017
#define IDC_BUTTON10                    1017
#define IDC_CBO_CUSTOM_OSD_STREAM       1017
#define IDC_DATE_BEG_Y                  1018
#define IDC_COMBO9                      1018
#define IDC_DATE_BEG_H                  1019
#define IDC_COMBO10                     1019
#define IDC_DATE_END_Y                  1020
#define IDC_DATE_END_H                  1021
#define IDC_LIST_FILE                   1022
#define IDC_DOWNLOAD_POS                1023
#define IDC_PLAY_POS                    1024
#define IDC_CBO_SLOT                    1025
#define IDC_TAB_SET                     1026
#define IDC_LIST_SMART_FILE             1026
#define IDC_SLD_BRIGHT                  1027
#define IDC_SLD_CONTRAST                1028
#define IDC_SLD_HUE                     1029
#define IDC_SLD_SATURATION              1030
#define IDC_CHECK1                      1031
#define IDC_CHECK2                      1032
#define IDC_SPIN1                       1032
#define IDC_CHECK3                      1033
#define IDC_SPIN2                       1033
#define IDC_SPIN3                       1034
#define IDC_SPIN4                       1035
#define IDC_SPIN5                       1036
#define IDC_SPIN6                       1037
#define IDC_CHECK_REC2                  1038
#define IDC_CHECK_REC3                  1039
#define IDC_CHECK_REC4                  1040
#define IDC_CHECK_REC5                  1041
#define IDC_CHECK_REC6                  1042
#define IDC_CHECK_REC7                  1043
#define IDC_CHECK_REC8                  1044
#define IDC_CHECK_REC9                  1045
#define IDC_CHECK_REC10                 1046
#define IDC_CHECK_REC11                 1047
#define IDC_CHECK_REC12                 1048
#define IDC_CHECK_REC13                 1049
#define IDC_CHECK_REC14                 1050
#define IDC_CHECK_REC15                 1051
#define IDC_CHECK_REC16                 1052
#define IDC_CHECK_OUT1                  1053
#define IDC_CHECK_OUT2                  1054
#define IDC_CHECK_OUT3                  1055
#define IDC_CHECK_OUT4                  1056
#define IDC_CHECK_OUT5                  1057
#define IDC_CHECK_OUT6                  1058
#define IDC_CHECK_OUT7                  1059
#define IDC_CHECK_OUT8                  1060
#define IDC_CHECK_OUT9                  1061
#define IDC_CHECK_OUT10                 1062
#define IDC_CHECK_OUT11                 1063
#define IDC_CHECK_OUT12                 1064
#define IDC_CHECK_OUT13                 1065
#define IDC_CHECK_OUT14                 1066
#define IDC_CHECK_OUT15                 1067
#define IDC_CHECK_OUT16                 1068
#define IDC_BUTTON5                     1069
#define IDC_CHECK_REC1                  1070
#define IDC_BUTTON11                    1070
#define IDC_SPIN7                       1071
#define IDC_SPIN8                       1072
#define IDC_SPIN9                       1073
#define IDC_SPIN10                      1074
#define IDC_SPIN11                      1075
#define IDC_SPIN12                      1076
#define IDC_EDIT_TIME1                  1079
#define IDC_EDIT_TIME7                  1080
#define IDC_EDIT_TIME3                  1081
#define IDC_EDIT_TIME2                  1082
#define IDC_LIST1                       1083
#define IDC_LST_DEVICE                  1084
#define IDC_LIST2                       1084
#define IDC_BTN_SEARCH                  1085
#define IDC_BUTTON_SMART                1086
#define IDC_BUTTON_SHOW_RECT            1087
#define IDC_BUTTON_SHOW_RECT2           1088
#define IDC_CHK_COLOR                   1092
#define IDC_CBO_YUV_BUF                 1093
#define IDC_EDT_CUR_YUV_BUF             1094
#define IDC_BTN_SNAP_BMP                1095
#define IDC_BTN_SNAP_JPG                1096
#define IDC_BTN_START_REC               1097
#define IDC_BTN_STOP_REC                1098
#define IDC_CHK_AUDIO_PREVIEW           1099
#define IDC_CBO_SCALE                   1100
#define IDC_CHK_REGALARM                1101
#define IDC_LST_ALARM                   1102
#define IDC_EDT_MAX_BPS                 1103
#define IDC_EDT_GOP                     1104
#define IDC_VOICE                       1104
#define IDC_CBO_DEFEND                  1106
#define IDC_CBO_CONNECTMODE             1107
#define IDC_BTN_AUTO_FOCUS              1108
#define IDC_VIDEO_IPC                   1109
#define IDC_CHK_RECT_ENABLE             1110
#define IDC_VLOST_OUT1                  1111
#define IDC_BTN_ENABLE_FLIP             1111
#define IDC_VLOST_OUT2                  1112
#define IDC_VLOST_OUT3                  1113
#define IDC_VLOST_OUT4                  1114
#define IDC_VLOST_OUT5                  1115
#define IDC_VLOST_OUT6                  1116
#define IDC_VLOST_OUT7                  1117
#define IDC_VLOST_OUT8                  1118
#define IDC_VLOST_OUT9                  1119
#define IDC_VLOST_OUT10                 1120
#define IDC_VLOST_OUT11                 1121
#define IDC_VLOST_OUT12                 1122
#define IDC_VLOST_OUT13                 1123
#define IDC_VLOST_OUT14                 1124
#define IDC_VLOST_OUT15                 1125
#define IDC_VLOST_OUT16                 1126
#define IDC_EDT_COM_ADDR                1127
#define IDC_BTN_COM_UP                  1128
#define IDC_BTN_COM_LEFT                1129
#define IDC_BTN_COM_DOWN                1130
#define IDC_BTN_COM_RIGHT               1131
#define IDC_BTN_COM_STOP                1132
#define IDC_CBO_COM_BRATE               1133
#define IDC_BTN_COM_ZOOM_IN             1134
#define IDC_BTN_COM_ZOOM_OUT            1135
#define IDC_CBO_FILE_T                  1136
#define IDC_CBO_FILE_TYPE               1136
#define IDC_BTN_COM_NEAR                1136
#define IDC_CHK_BLACKLIGHTING           1137
#define IDC_CBO_BLACKLIGHTING           1138
#define IDC_TXT_BRIGHT                  1139
#define IDC_TXT_CONTRAST                1140
#define IDC_EDT_SERIAL_NO               1140
#define IDC_TXT_SATURATION              1141
#define IDC_TXT_HUE                     1142
#define IDC_CHK_SERIAL_SEND             1143
#define IDC_CBO_COM_PARITY              1144
#define IDC_BTN_COM_FAR                 1145
#define IDC_CBO_COM_SPEED               1146
#define IDC_CBO_COM_PRESET_EXEC         1147
#define IDC_CBO_COM_PRESET_SETUP        1148
#define IDC_CBO_COM_PRESET              1149
#define IDC_SLD_SHARPEN                 1150
#define IDC_CHK_SHARPEN_ENABLE          1151
#define IDC_TXT_SHARPEN                 1152
#define IDC_CHK_SHARPEN_AUTO            1153
#define IDC_CBO_ALARMOUT                1154
#define IDC_BTN_ALARMOUT_START          1155
#define IDC_BTN_ALARMOUT_STOP           1156
#define IDC_VIDEO_MASK                  1156
#define IDC_CHK_MASK_ENABLE             1157
#define IDC_CHK_ANALYZE_ENABLE          1158
#define IDC_CBO_ANALYZE_SLOT            1159
#define IDC_EDT_ANALYZE_SCENE_CHANGED   1160
#define IDC_EDT_ANALYZE_SCENE_OCCLUDED  1161
#define IDC_EDT_ANALYZE_FOCUS_CHANGE    1162
#define IDC_CHK_CUSTOM_OSD_NAME_ENABLE  1163
#define IDC_CHK_CUSTOM_OSD_NAME_OUTLINE 1164
#define IDC_CHK_CUSTOM_OSD_DATE_ENABLE  1165
#define IDC_CHK_CUSTOM_OSD_DATE_OUTLINE 1166
#define IDC_CBO_CUSTOM_OSD_SLOT         1167
#define IDC_EDT_CUSTOM_OSD_NAME_LEFT    1168
#define IDC_EDT_CUSTOM_OSD_NAME_TOP     1169
#define IDC_CBO_CUSTOM_OSD_NAME_COLOR   1170
#define IDC_EDT_CUSTOM_OSD_NAME_FONT    1171
#define IDC_CBO_CUSTOM_OSD_NAME_ALPHA   1172
#define IDC_EDT_CUSTOM_OSD_NAME_ROW     1173
#define IDC_EDT_CUSTOM_OSD_DATE_LEFT    1174
#define IDC_EDT_CUSTOM_OSD_DATE_TOP     1175
#define IDC_CBO_CUSTOM_OSD_DATE_COLOR   1176
#define IDC_CBO_CUSTOM_OSD_DATE_ALPHA   1177
#define IDC_CHK_CUSTOM_DATE_SHOW_WEEK   1178
#define IDC_CBO_CUSTOM_OSD_DATE_MODE    1179
#define IDC_CUSTOM_OSD_VIDEO            1180
#define IDC_CHK_CUSTOM_OSD_NAME2_ENABLE 1181
#define IDC_CHK_AUDIO_ENHANCE           1181
#define IDC_EDT_CUSTOM_OSD_NAME2_LEFT   1182
#define IDC_CHK_ENABLE_FLIP             1182
#define IDC_CBO_CUSTOM_OSD_NAME2_COLOR  1183
#define IDC_RADIO1                      1183
#define IDC_EDT_CUSTOM_OSD_NAME2_FONT   1184
#define IDC_RADIO2                      1184
#define IDC_CBO_REMOTE_TYPE             1184
#define IDC_EDT_CUSTOM_OSD_NAME2_ROW    1185
#define IDC_RADIO3                      1185
#define IDC_EDT_RTSP_URI                1185
#define IDC_EDT_CUSTOM_OSD_NAME2_TOP    1186
#define IDC_RADIO4                      1186
#define IDC_BTN_DELETE_FILE             1186
#define IDC_CHK_CUSTOM_OSD_NAME2_OUTLINE 1187
#define IDC_CBO_CUSTOM_OSD_NAME2_ALPHA  1188
#define IDC_VIDEO_KAOQING2              1188
#define IDC_IPADDRESS_KAOQING           1189
#define IDC_BTLOGIN_KAOQING             1190
#define IDC_STATIC1                     1192
#define IDC_USERNAME                    1193
#define IDC_PASSWORD                    1194
#define IDC_DATETIMEPICKER1             1198
#define IDC_STATIC_BMP                  1199
#define IDC_STATIC_RENTOU               1200
#define IDC_STATIC_VIDEO                1201
#define IDC_TREE1                       1202

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
